language: smalltalk
sudo: required

os:
- linux

install:
 - pip install benchupload

smalltalk:
- Pharo-5.0
- Pharo-6.0

script:
- $SMALLTALK_CI_HOME/run.sh

after_success:
 - benchupload --dir=$SMALLTALK_CI_HOME

after_failure:
  - benchupload --dir=$SMALLTALK_CI_HOME
